name: Test Release Creation

on:
  push:
    branches:
      - 'feature/automated_release'  # Trigger on branch push

jobs:
  test-release:
    runs-on: ubuntu-latest  # No need for Windows if just testing the release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test GitHub Release Creation
        uses: softprops/action-gh-release@v1
        with:
          files: requirements.txt  # Use an existing file in your repo
          tag_name: v1.0.0-test  # Static tag name for testing
          name: Test Release v1.0.0
          body: "This is a test release to verify token permissions."
          repository: LANCHUT/Finao  # Target repository
        env:
          GITHUB_TOKEN: ${{ secrets.FINAO_TOKEN }}  # Use the secret directly
