name: Build and Publish EXE on Release

on:
  push:
#    tags:
#      - 'v*'
    branches:
          - 'feature/automated_release'
jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
#
#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.11'
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#          pip install pyinstaller
#
#      - name: Build EXE with PyInstaller
#        run: |
#          python -m PyInstaller --onefile --windowed --name=finao --icon=assets/icons/Finao.ico main.py
#
#      - name: Test Software
#        run: |
#          .\dist\finao.exe
#
#      - name: Upload EXE as artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: Finao_Software
#          path: dist/finao.exe


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
#          files: dist/finao.exe
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "New Release of Finao ${{ github.ref_name }}"
          repository: LANCHUT/Finao
          token: '${{ secrets.FINAO_TOKEN }}'
