name: Test Release Creation

on:
  push:
#    tags:
#      - 'v*'
    branches:
      - 'feature/automated_release'
jobs:
  test-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          python -m PyInstaller --onefile --windowed --name=finao --icon=assets/icons/Finao.ico Main.py

      - name: List dist directory contents
        run: dir dist

      - name: Check if finao.exe exists
        run: if not exist "dist\finao.exe" exit 1

      - name: Test Software
        run: |
          .\dist\finao.exe
          if %ERRORLEVEL% neq 0 exit 1
        shell: cmd

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Finao_Software
          path: dist/finao.exe

      - name: Publish new version Finao Software
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.FINAO_TOKEN }}
          file: ${{ github.workspace }}\dist\finao.exe
          asset_name: Release ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          overwrite: true
          body: "New Release of Finao ${{ github.ref_name }}"
          repo_name: LANCHUT/Finao